### ISSUE TITLE
Breaking Change on Vigilance Repo - Themes Will Need a Fix

### ISSUE THREAD

**Issue by proudmuslim-dev** [proudmuslim-dev/vigilance-themes#15]
For further info, see [this commit](https://github.com/Sk1erLLC/Vigilance/commit/b8bf1cf6c35574cb6f9fbc2e6dc8177d98776bbc).

New default config:

```toml
[color_scheme]

	[color_scheme.palette]
		bright_divider = "255,151,151,151"
		mid_text = "255,187,187,187"
		bright_highlight = "255,50,50,50"
		search_bar_background = "255,27,28,33"
		light_background = "255,32,32,33"
		bright_text = "255,255,255,255"
		dark_divider = "255,50,50,50"
		dark_highlight = "255,27,28,33"
		dark_text = "255,119,119,121"
		accent = "255,1,165,82"
		transparent = "0,0,0,0"
		modal_background = "100,0,0,0"
		highlight = "255,33,34,38"
		outline = "255,48,48,49"
		divider = "255,80,80,80"
		background = "255,22,22,24"
		success = "255,1,165,82"
		scroll_bar = "255,45,45,45"
		dark_background = "255,10,10,11"
		warning = "255,239,83,80"
		disabled = "255,80,80,80"
```
